/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/test_math.test" instead.
 */

#include <check.h>

#line 1 "tests/test_math.test"
/*DO 
  checkmk tests/test_math.test >tests/test_math.c
*/
#define fuenf 5
#include "../include/hhmpcmath.h"
#include "../include/mpcincmtxops.h"

START_TEST(mtx_out_test)
{
#line 9
    real_t test_a[] = {2., 2., 3., 3.}, test_b[] = {4., 4.}; 
    fail_unless(mtx_out(test_a, 2., 2., test_b) == 16., "mtx_out function confuses me");

}
END_TEST

START_TEST(simple_sum_test)
{
#line 13
    fail_unless(simple_sum(3, 2) == fuenf, "sum function borked");
    fail_unless(simple_sum(-3, 2) == -1, "sum function borked");
    fail_unless(simple_sum(3, -2) == 1, "sum function borked");
    fail_unless(simple_sum(-3, -2) == -fuenf, "sum function borked");
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, mtx_out_test);
    tcase_add_test(tc1_1, simple_sum_test);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
