/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/test_math.test" instead.
 */

#include <check.h>

#line 1 "tests/test_math.test"
/*DO 
  checkmk tests/test_math.test >tests/test_math.c
*/
#define fuenf 5
#include "../include/hhmpcmath.h"
#include "../include/hhmpcusefull.h"

START_TEST(cholesky_test)
{
#line 9
    real_t sol[9];
    real_t mtx[] = {4., 2., 0., 2., 5., 2., 0., 2., 5.};
    real_t sol_ref[] = {2., 0., 0., 1., 2., 0., 0., 1., 2.};
    uint32_t dim = 3;
    cholesky(sol, mtx, dim);
    fail_unless(mtx_cmp(sol, sol_ref, 9, 0) == 0, "cholesky failed");
    
}
END_TEST

START_TEST(fwd_subst_test)
{
#line 17
    real_t sol[4]; 
    real_t test_a[] = {2., 0., 3., 1.}, test_b[] = {4., 8., 4., 8.};
    real_t sol_ref[] = {2., 4., -2., -4.};
    fwd_subst(sol, test_a, 2, test_b, 2);
    fail_unless(mtx_cmp(sol, sol_ref, 4, 0) == 0, "forward substitution failed");

}
END_TEST

START_TEST(bwd_subst_test)
{
#line 24
    real_t sol[4]; 
    real_t test_a[] = {4., 1., 0., 2.}, test_b[] = {4., 8., 4., 8.};
    real_t sol_ref[] = {.5, 1., 2., 4.};
    bwd_subst(sol, test_a, 2, test_b, 2);
    fail_unless(mtx_cmp(sol, sol_ref, 4, 0) == 0, "backward substitution failed");

}
END_TEST

START_TEST(mtx_out_test)
{
#line 31
    real_t test_a[] = {2., 2., 3., 3.}, test_b[] = {4., 4.}; 
    fail_unless(mtx_out(test_a, 2, 2, test_b) == 16., "mtx_out function confuses me");

}
END_TEST

START_TEST(simple_sum_test)
{
#line 35
    fail_unless(simple_sum(3, 2) == fuenf, "sum function borked");
    fail_unless(simple_sum(-3, 2) == -1, "sum function borked");
    fail_unless(simple_sum(3, -2) == 1, "sum function borked");
    fail_unless(simple_sum(-3, -2) == -fuenf, "sum function borked");
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, cholesky_test);
    tcase_add_test(tc1_1, fwd_subst_test);
    tcase_add_test(tc1_1, bwd_subst_test);
    tcase_add_test(tc1_1, mtx_out_test);
    tcase_add_test(tc1_1, simple_sum_test);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
